# Generated by Django 3.1.7 on 2021-02-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_code', models.CharField(max_length=20, unique=True, verbose_name='Код поезда')),
                ('trip_time', models.IntegerField(verbose_name='Время в пути')),
                ('train_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Конечная_остановка', to='route.cities')),
                ('train_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Место_старта', to='route.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=30, verbose_name='имя маршрута')),
                ('route_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Конец_маршрута', to='route.cities')),
                ('route_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Начало_маршрута', to='route.cities')),
            ],
        ),
    ]
