# Generated by Django 3.1.7 on 2021-02-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='cities',
            name='description',
            field=models.TextField(default='Информация появится чуть позже...', verbose_name='Описание города'),
        ),
        migrations.AddField(
            model_name='cities',
            name='photo',
            field=models.ImageField(default='img/default_city.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(max_length=50, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='имя маршрута'),
        ),
    ]
