# Generated by Django 3.1.7 on 2021-02-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20210224_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='photo',
            field=models.ImageField(default='img/default_city.jpg', upload_to='photos/'),
        ),
    ]
