# Generated by Django 3.1.7 on 2021-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_auto_20210224_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='photo',
            field=models.ImageField(default='photos/default_city.jpg', upload_to='photos'),
        ),
    ]
