# Generated by Django 3.1.7 on 2021-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_auto_20210226_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
