# Generated by Django 3.1.7 on 2021-03-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_auto_20210304_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trains',
            options={'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
    ]
