# Generated by Django 3.1.7 on 2021-03-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_auto_20210304_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_code', models.CharField(max_length=20, unique=True, verbose_name='Код рейса')),
                ('trip_time', models.PositiveIntegerField(verbose_name='Время в пути')),
                ('plain_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plain_end_set', to='route.cities', verbose_name='Конечная остановка')),
                ('plain_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plain_start_set', to='route.cities', verbose_name='Место старта')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.DeleteModel(
            name='Trains',
        ),
    ]
